apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
    meta.helm.sh/release-name: harbor
    meta.helm.sh/release-namespace: marketplace
  creationTimestamp: "2021-11-25T07:43:09Z"
  generation: 3
  labels:
    app: harbor
    app.kubernetes.io/managed-by: Helm
    chart: harbor
    component: portal
    heritage: Helm
    release: harbor
  name: harbor-portal
  namespace: marketplace
  resourceVersion: "158316871"
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: harbor
      component: portal
      release: harbor
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        checksum/tls: 419d4c744a70fea4f98a326a94cfee38774bafdea8a03f2ac7d19de6ced6acaa
      creationTimestamp: null
      labels:
        app: harbor
        component: portal
        release: harbor
    spec:
      automountServiceAccountToken: false
      containers:
      - image: goharbor/harbor-portal:v2.4.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 8443
            scheme: HTTPS
          initialDelaySeconds: 300
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: portal
        ports:
        - containerPort: 8443
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 8443
            scheme: HTTPS
          initialDelaySeconds: 1
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/nginx/nginx.conf
          name: portal-config
          subPath: nginx.conf
        - name: rebranding
          mountPath: /usr/share/nginx/html/setting.json
          subPath: setting.json
        - name: rebranding
          mountPath: /usr/share/nginx/html/images/harbor-logo.svg
          subPath: harbor-logo.svg
        - name: rebranding
          mountPath: /usr/share/nginx/html/images/bg-pattern.jpg
          subPath: bg-pattern.jpg
        - name: rebranding
          mountPath: /usr/share/nginx/html/favicon.ico
          subPath: favicon.ico
        - mountPath: /etc/harbor/ssl/portal
          name: portal-internal-certs
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 10000
        runAsUser: 10000
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: harbor-portal
        name: portal-config
      - configMap:
          defaultMode: 420
          name: rebranding
        name: rebranding
      - name: portal-internal-certs
        secret:
          defaultMode: 420
          secretName: harbor-portal-internal-tls
